// 모바일 완료예정일 기본값
const DEFAULT_MOBILE_DUE_AT = '2026-02-28'
const TODAY = '2026-03-17'

export const PUB_MENUS = [
  // ========== 포털서비스메인 (PSM*) ==========
  {
    service: 'portal',
    userType: [],
    levels: ['HOME'],
    screenId: 'PSMHOM010U',
    name: '포털 메인',
    type: '화면',
    desc: '포털 메인',
    completedAt: '2026-04-20',
    mobileApply: '구분 없음',
    mobileAttr: '반응형',
    nature: '특화',
  },
  {
    service: 'portal',
    userType: [],
    levels: ['Solutions', 'Digital Axis'],
    screenId: 'PSMSOL010U',
    name: '디지털 전환',
    type: '화면',
    desc: '디지털 전환 소개',
    completedAt: TODAY,
    mobileApply: '구분 없음',
    mobileAttr: '반응형',
    nature: '특화',
  },
  {
    service: 'portal',
    userType: [],
    levels: ['Solutions', 'Electronic Bill of Lading'],
    screenId: 'PSMSOL020U',
    name: 'eBL 소개',
    type: '화면',
    desc: 'eBL 특장점 소개',
    completedAt: TODAY,
    mobileApply: '구분 없음',
    mobileAttr: '반응형',
    nature: '특화',
  },
  {
    service: 'portal',
    userType: [],
    levels: ['Solutions', 'Negotiation'],
    screenId: 'PSMSOL030U',
    name: '매입 관리 소개',
    type: '화면',
    desc: '매입 프로세스 소개',
    completedAt: TODAY,
    mobileApply: '구분 없음',
    mobileAttr: '반응형',
    nature: '특화',
  },
  {
    service: 'portal',
    userType: [],
    levels: ['Solutions', 'Presentation'],
    screenId: 'PSMSOL040U',
    name: '매입 심사 소개',
    type: '화면',
    desc: '매입 심사 소개',
    completedAt: TODAY,
    mobileApply: '구분 없음',
    mobileAttr: '반응형',
    nature: '특화',
  },
  {
    service: 'portal',
    userType: [],
    levels: ['Platform', 'Technology'],
    screenId: 'PSMPLT010U',
    name: '기술 소개',
    type: '화면',
    desc: '기술 관련 소개',
    completedAt: TODAY,
    mobileApply: '구분 없음',
    mobileAttr: '반응형',
    nature: '특화',
  },
  {
    service: 'portal',
    userType: [],
    levels: ['Platform', 'Security'],
    screenId: 'PSMPLT020U',
    name: '보안 소개',
    type: '화면',
    desc: '보안 관련 소개',
    completedAt: TODAY,
    mobileApply: '구분 없음',
    mobileAttr: '반응형',
    nature: '특화',
  },
  {
    service: 'portal',
    userType: [],
    levels: ['Platform', 'Industrial Standards'],
    screenId: 'PSMPLT030U',
    name: '산업 표준',
    type: '화면',
    desc: '산업 표준 소개',
    completedAt: TODAY,
    mobileApply: '구분 없음',
    mobileAttr: '반응형',
    nature: '특화',
  },
  {
    service: 'portal',
    userType: [],
    levels: ['Resources', 'FAQ'],
    screenId: 'PSMRSC010U',
    name: 'FAQ',
    type: '화면',
    desc: '자주 묻는 질문',
    completedAt: TODAY,
    mobileApply: '구분 없음',
    mobileAttr: '반응형',
    nature: '특화',
  },
  {
    service: 'portal',
    userType: [],
    levels: ['Resources', 'Tutorials'],
    screenId: 'PSMRSC020U',
    name: '튜토리얼',
    type: '화면',
    desc: '서비스 튜토리얼',
    completedAt: TODAY,
    mobileApply: '구분 없음',
    mobileAttr: '반응형',
    nature: '특화',
  },
  {
    service: 'portal',
    userType: [],
    levels: ['Company', 'About KTNET'],
    screenId: 'PSMCPN010U',
    name: 'KTNET 소개',
    type: '화면',
    desc: 'KTNET 소개',
    completedAt: TODAY,
    mobileApply: '구분 없음',
    mobileAttr: '반응형',
    nature: '특화',
  },
  {
    service: 'portal',
    userType: [],
    levels: ['Company', 'Contact US'],
    screenId: 'PSMCPN020U',
    name: '문의하기',
    type: '화면',
    desc: '문의하기',
    completedAt: TODAY,
    mobileApply: '구분 없음',
    mobileAttr: '반응형',
    nature: '특화',
  },
  {
    service: 'portal',
    userType: [],
    levels: ['Sign in'],
    screenId: 'PSMSIN010U',
    name: '로그인',
    type: '화면',
    desc: '아이디(이메일), 비밀번호',
    completedAt: TODAY,
    mobileApply: '구분 없음',
    mobileAttr: '반응형',
    nature: '공통',
  },
  {
    service: 'portal',
    userType: [],
    levels: ['Sign in', 'Login Popup'],
    screenId: 'PSMSIN050P',
    name: '로그인(팝업)',
    type: '팝업화면',
    desc: '아이디(이메일), 비밀번호 (이용 중 세션 연장)',
    completedAt: '2026-04-20',
    mobileApply: '구분 없음',
    mobileAttr: '반응형',
    nature: '공통',
  },
  {
    service: 'portal',
    userType: [],
    levels: ['Sign in', 'ID Search'],
    screenId: 'PSMSIN020U',
    name: 'ID 찾기',
    type: '화면',
    desc: '사용자명, 핸드폰 번호',
    completedAt: TODAY,
    mobileApply: '구분 없음',
    mobileAttr: '반응형',
    nature: '공통',
  },
  {
    service: 'portal',
    userType: [],
    levels: ['Sign in', 'ID Search', 'ID Result'],
    screenId: 'PSMSIN030P',
    parentScreenId: 'PSMSIN020U',
    name: 'ID 찾기 결과',
    type: '팝업화면',
    desc: '찾기 결과 마스킹 처리',
    completedAt: TODAY,
    mobileApply: '구분 없음',
    mobileAttr: '반응형',
    nature: '공통',
  },
  {
    service: 'portal',
    userType: [],
    levels: ['Sign in', 'Reset Password'],
    screenId: 'PSMSIN040U',
    name: '비밀번호 재발급',
    type: '화면',
    desc: '아이디(이메일), 비밀번호',
    completedAt: TODAY,
    mobileApply: '구분 없음',
    mobileAttr: '반응형',
    nature: '공통',
  },
  {
    service: 'portal',
    userType: [],
    levels: ['Register'],
    screenId: 'PSMREG010U',
    name: '회원가입',
    type: '화면',
    desc: '회원가입 - 비번찾기, 변경, 등 기능..',
    completedAt: TODAY,
    mobileApply: '구분 없음',
    mobileAttr: '반응형',
    nature: '공통',
  },
  {
    service: 'portal',
    userType: [],
    levels: ['Register', 'Registed Information'],
    screenId: 'PSMREG020U',
    name: 'Registed Information',
    type: '화면',
    desc: '회원가입 승인 대기중, 로그인 시도시 안내 화면',
    completedAt: '2026-04-02',
    mobileApply: '구분 없음',
    mobileAttr: '반응형',
    nature: '공통',
  },
  // {
  //   service: 'portal',
  //   userType: [],
  //   levels: ['Register', 'Register Coupon'],
  //   screenId: 'EBLPAY030P',
  //   parentScreenId: 'PSMREG010U',
  //   name: '쿠폰 등록',
  //   type: '팝업화면',
  //   desc: '쿠폰번호를 입력하여 쿠폰 등록 / 이메일로 쿠폰 번호 전송',
  //   completedAt: '',
  //   mobileApply: '구분 없음',
  //   mobileAttr: '반응형',
  //   nature: '공통',
  // },
  {
    service: 'portal',
    userType: [],
    levels: ['Privacy Policy'],
    screenId: 'PSMPPY010U',
    name: '개인정보 처리방침',
    type: '화면',
    desc: '개인정보 처리방침 안내',
    completedAt: '2026-04-20',
    mobileApply: '구분 없음',
    mobileAttr: '반응형',
    nature: '공통',
  },
  {
    service: 'portal',
    userType: [],
    levels: ['System'],
    screenId: 'PSMSYS010U',
    name: '시스템 점검',
    type: '화면',
    desc: '시스템 점검 안내 페이지',
    completedAt: '2026-04-20',
    mobileApply: '구분 없음',
    mobileAttr: '반응형',
    nature: '공통',
  },
  {
    service: 'portal',
    userType: [],
    levels: ['System'],
    screenId: 'PSMSYS500U',
    name: '500 에러 테스트',
    type: '화면',
    desc: 'error.vue 500 에러 렌더링 확인용 페이지',
    completedAt: '2026-04-20',
    mobileApply: '구분 없음',
    mobileAttr: '반응형',
    nature: '공통',
  },
  {
    service: 'portal',
    userType: [],
    levels: ['System'],
    screenId: 'PSMSYS404T',
    name: '404 에러 테스트',
    type: '화면',
    desc: 'error.vue 404 에러 렌더링 확인용 페이지',
    completedAt: '2026-04-20',
    mobileApply: '구분 없음',
    mobileAttr: '반응형',
    nature: '공통',
    routePath: '/not-found-test',
  },

  // ========== eBL서비스 Dashboard (EBLCDB, EBLSDB, EBLBDB) ==========
  {
    service: 'ebl',
    userType: ['선사'],
    levels: ['Dashboard'],
    screenId: 'EBLCDB010U',
    name: '대시보드',
    type: '화면',
    desc: '선사용 대시보드',
    completedAt: '2026-02-06',
    mobileApply: '축소 적용',
    mobileAttr: 'Body',
    nature: '특화',
    mobileCompletedAt: '2026-02-12',
  },
  {
    service: 'ebl',
    userType: ['화주'],
    levels: ['Dashboard'],
    screenId: 'EBLSDB010U',
    name: '대시보드',
    type: '화면',
    desc: '화주용 대시보드',
    completedAt: '2026-02-06',
    mobileApply: '축소 적용',
    mobileAttr: 'Body',
    nature: '특화',
    mobileCompletedAt: '2026-02-12',
  },
  {
    service: 'ebl',
    userType: ['은행'],
    levels: ['Dashboard'],
    screenId: 'EBLBDB010U',
    name: '대시보드',
    type: '화면',
    desc: '은행용 대시보드',
    completedAt: '2026-02-06',
    mobileApply: '축소 적용',
    mobileAttr: 'Body',
    nature: '특화',
    mobileCompletedAt: '2026-02-12',
  },

  // ========== eBL서비스 (선사) Documents - Create B/L ==========
  {
    service: 'ebl',
    userType: ['선사'],
    levels: ['Documents', 'Create B/L'],
    screenId: 'EBLCDC010U',
    name: 'eBL 작성',
    type: '화면',
    desc: 'eBL 수기 작성(T&C 등록) 및 발행',
    completedAt: '2026-02-05',
    mobileApply: '미적용',
    mobileAttr: 'N/A',
    nature: '특화',
  },
  {
    service: 'ebl',
    userType: ['선사'],
    levels: ['Documents', 'Create B/L', 'Recipient'],
    screenId: 'EBLCDC020P',
    parentScreenId: 'EBLCDC010U',
    name: '수신인 지정',
    type: '팝업화면',
    desc: '수신인 지정(최초 소유권자)',
    completedAt: '2026-02-05',
    mobileApply: '미적용',
    mobileAttr: 'N/A',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: ['선사'],
    levels: ['Documents', 'Create B/L', 'Container'],
    screenId: 'EBLCDC090U',
    parentScreenId: 'EBLCDC010U',
    name: '컨테이너 정보',
    type: '화면',
    desc: '컨테이너 정보 작성(다수 작성 가능)',
    completedAt: '2026-02-05',
    mobileApply: '미적용',
    mobileAttr: 'N/A',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: ['선사'],
    levels: ['Documents', 'Create B/L', 'Terms & Conditions'],
    screenId: 'EBLCDC040U',
    parentScreenId: 'EBLCDC010U',
    name: '이면약관 작성',
    type: '화면',
    desc: '이면약관 불러오기 및 수기작성',
    completedAt: '2026-02-05',
    mobileApply: '미적용',
    mobileAttr: 'N/A',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: ['선사'],
    levels: ['Documents', 'Create B/L', 'Enter Password'],
    screenId: 'EBLCDC100P',
    parentScreenId: 'EBLCDC010U',
    name: '비밀번호 입력',
    type: '팝업화면',
    desc: '비밀번호를 입력하여 발행 완료',
    completedAt: '2026-02-05',
    mobileApply: '미적용',
    mobileAttr: 'N/A',
    nature: '공통',
  },

  // ========== eBL서비스 (선사) Documents - Sent ==========
  {
    service: 'ebl',
    userType: ['선사'],
    levels: ['Documents', 'Sent'],
    screenId: 'EBLCDC050U',
    name: '발신 목록',
    type: '화면',
    desc: 'eBL 발신 내역',
    completedAt: '2026-02-05',
    mobileApply: '필수 적용',
    mobileAttr: 'Body',
    mobileCompletedAt: '2026-02-24',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: ['선사'],
    levels: ['Documents', 'Sent', 'B/L Detail', 'B/L Info'],
    screenId: 'EBLCDC110P',
    parentScreenId: 'EBLCDC050U',
    name: 'eBL 상세',
    type: '팝업화면',
    desc: 'eBL 상세 정보',
    completedAt: '2026-02-05',
    mobileApply: '필수 적용',
    mobileAttr: 'Pop Up',
    mobileCompletedAt: '2026-02-24',
    nature: '특화',
  },
  {
    service: 'ebl',
    userType: ['선사'],
    levels: ['Documents', 'Sent', 'B/L Detail', 'Container Info'],
    screenId: 'EBLCDC120P',
    parentScreenId: 'EBLCDC050U',
    name: '컨테이너 상세',
    type: '팝업화면',
    desc: '컨테이너 상세 정보',
    completedAt: '2026-02-05',
    mobileApply: '필수 적용',
    mobileAttr: 'Pop Up',
    mobileCompletedAt: '2026-02-24',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: ['선사'],
    levels: ['Documents', 'Sent', 'B/L Detail', 'T&C Info'],
    screenId: 'EBLCDC130P',
    parentScreenId: 'EBLCDC050U',
    name: '이면약관 상세',
    type: '팝업화면',
    desc: '이면약관 상세 정보',
    completedAt: '2026-02-05',
    mobileApply: '필수 적용',
    mobileAttr: 'Pop Up',
    mobileCompletedAt: '2026-02-24',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: ['선사'],
    levels: ['Documents', 'Sent', 'eBL Transaction'],
    screenId: 'EBLCDC140P',
    parentScreenId: 'EBLCDC050U',
    name: '거래 이력',
    type: '팝업화면',
    desc: 'eBL 거래 상태 이력',
    completedAt: '2026-02-05',
    mobileApply: '필수 적용',
    mobileAttr: 'Pop Up',
    mobileCompletedAt: '2026-02-24',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: ['선사'],
    levels: ['Documents', 'Sent', 'Preview'],
    screenId: 'EBLCDC030P',
    parentScreenId: 'EBLCDC050U',
    name: 'eBL 미리보기',
    type: '팝업화면',
    desc: 'eBL 미리보기',
    completedAt: '2026-02-05',
    mobileApply: '미적용',
    mobileAttr: 'N/A',
    mobileCompletedAt: '2026-02-24',
    nature: '특화',
  },

  // ========== eBL서비스 (선사) Documents - Draft ==========
  {
    service: 'ebl',
    userType: ['선사'],
    levels: ['Documents', 'Draft'],
    screenId: 'EBLCDC060U',
    name: '임시저장 목록',
    type: '화면',
    desc: 'API를 통해 연동된 BL 노출 / 작성중인 BL',
    completedAt: '2026-02-05',
    mobileApply: '필수 적용',
    mobileAttr: 'Body',
    mobileCompletedAt: '2026-02-28',
    nature: '공통',
  },

  // ========== eBL서비스 (선사) Documents - Incoming ==========
  {
    service: 'ebl',
    userType: ['선사'],
    levels: ['Documents', 'Incoming'],
    screenId: 'EBLCDC070U',
    name: '요청 목록',
    type: '화면',
    desc: '요청사항 목록(Approve/Reject) / Amend history 관리 필요',
    completedAt: '2026-02-05',
    mobileApply: '필수 적용',
    mobileAttr: 'Body',
    mobileCompletedAt: '2026-02-28',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: ['선사'],
    levels: ['Documents', 'Incoming', 'Paper Sign'],
    screenId: 'EBLCDC150P',
    parentScreenId: 'EBLCDC070U',
    name: '종이발급 서명',
    type: '팝업화면',
    desc: '종이발급 요청 수락 후 서명 진행',
    completedAt: '2026-02-05',
    mobileApply: '필수 적용',
    mobileAttr: 'Bottom Sheet',
    mobileCompletedAt: '2026-02-28',
    nature: '공통',
  },

  // ========== eBL서비스 (선사) Documents - Archive ==========
  {
    service: 'ebl',
    userType: ['선사'],
    levels: ['Documents', 'Archive'],
    screenId: 'EBLCDC080U',
    name: '전송 이력 조회',
    type: '화면',
    desc: '전송 이력 조회(송/수신일시, 수신인, BL상태 등)',
    completedAt: '2026-02-05',
    mobileApply: '필수 적용',
    mobileAttr: 'Body',
    mobileCompletedAt: '2026-02-24',
    nature: '공통',
  },

  // ========== eBL서비스 (화주/은행) Documents - Compose Envelope ==========
  {
    service: 'ebl',
    userType: ['화주', '은행'],
    levels: ['Documents', 'Compose Envelope'],
    screenId: 'EBLDOC010U',
    name: 'Envelope 생성',
    type: '화면',
    desc: '*Transfer, Amend, Delivery 등 외부 파트너에게 발송되어지는 모든 종류의 문서/메시지는 Envelope 생성하여 발송',
    completedAt: '2026-02-04',
    mobileApply: '미적용',
    mobileAttr: 'N/A',
    nature: '특화',
  },
  {
    service: 'ebl',
    userType: ['화주'],
    levels: ['Documents', 'Compose Envelope', 'Amend'],
    screenId: 'EBLDOC040P',
    parentScreenId: 'EBLDOC010U',
    name: 'eBL 수정 요청',
    type: '팝업화면',
    desc: 'eBL 수정요청 (수신인 : Carrier)',
    completedAt: '2026-02-03',
    mobileApply: '필수 적용',
    mobileAttr: 'Pop Up',
    mobileCompletedAt: '2026-03-05',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: ['화주'],
    levels: ['Documents', 'Compose Envelope', 'Switch to Paper'],
    screenId: 'EBLDOC090P',
    parentScreenId: 'EBLDOC010U',
    name: '종이 선하증권 변환 요청',
    type: '팝업화면',
    desc: '종이 선하증권으로 변환 (수신인 : Carrier)',
    completedAt: '2026-02-03',
    mobileApply: '필수 적용',
    mobileAttr: 'Pop Up',
    mobileCompletedAt: '2026-03-05',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: ['화주'],
    levels: ['Documents', 'Compose Envelope', 'Surrender'],
    screenId: 'EBLDOC070P',
    parentScreenId: 'EBLDOC010U',
    name: 'eBL 써랜더 요청',
    type: '팝업화면',
    desc: '화물 인도 목적의 eBL 써렌더 요청 (수신인 : Carrier)',
    completedAt: '2026-02-03',
    mobileApply: '필수 적용',
    mobileAttr: 'Pop Up',
    mobileCompletedAt: '2026-03-05',
    nature: '공통',
  },

  // ========== eBL서비스 (화주/은행) Documents - Inbox ==========
  {
    service: 'ebl',
    userType: ['화주', '은행'],
    levels: ['Documents', 'Inbox'],
    screenId: 'EBLDOC030U',
    name: '수신함',
    type: '화면',
    desc: '수신함 *사용자 앞으로 발행된 eBL, Envelope',
    completedAt: '2026-02-03',
    mobileApply: '필수 적용',
    mobileAttr: 'Body',
    mobileCompletedAt: '2026-02-24',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: ['화주', '은행'],
    levels: ['Documents', 'Inbox', 'B/L Select'],
    screenId: 'EBLDOC140P',
    parentScreenId: 'EBLDOC030U',
    name: 'B/L 선택',
    type: '팝업화면',
    desc: '수신 받은 eBL 선택',
    completedAt: '2026-02-03',
    mobileApply: '미적용',
    mobileAttr: 'N/A',
    nature: '공통',
  },

  // ========== eBL서비스 (화주/은행) Documents - Sent ==========
  {
    service: 'ebl',
    userType: ['화주', '은행'],
    levels: ['Documents', 'Sent'],
    screenId: 'EBLDOC100U',
    name: '발신 목록',
    type: '화면',
    desc: 'Envelope 발신 내역',
    completedAt: '2026-02-03',
    mobileApply: '미적용',
    mobileAttr: 'N/A',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: ['화주', '은행'],
    levels: ['Documents', 'Sent', 'Envelope Detail'],
    screenId: 'EBLDOC150P',
    parentScreenId: 'EBLDOC100U',
    name: 'Envelope 상세',
    type: '화면',
    desc: 'Envelope 상세 정보',
    completedAt: '2026-02-03',
    mobileApply: '미적용',
    mobileAttr: 'N/A',
    nature: '특화',
  },

  // ========== eBL서비스 (화주/은행) Documents - Draft ==========
  {
    service: 'ebl',
    userType: ['화주', '은행'],
    levels: ['Documents', 'Draft'],
    screenId: 'EBLDOC110U',
    name: '임시저장 목록',
    type: '화면',
    desc: '작성중인 Envelope',
    completedAt: '2026-02-03',
    mobileApply: '필수 적용',
    mobileAttr: 'N/A',
    nature: '공통',
  },

  // ========== eBL서비스 (화주/은행) Documents - Incoming ==========
  {
    service: 'ebl',
    userType: ['화주', '은행'],
    levels: ['Documents', 'Incoming'],
    screenId: 'EBLDOC130U',
    name: '요청 목록',
    type: '화면',
    desc: '양도 요청 목록(Approve/Reject)',
    completedAt: '2026-02-03',
    mobileApply: '필수 적용',
    mobileAttr: 'Body',
    mobileCompletedAt: '2026-02-28',
    nature: '공통',
  },

  // ========== eBL서비스 (화주/은행) Documents - Archive ==========
  {
    service: 'ebl',
    userType: ['화주', '은행'],
    levels: ['Documents', 'Archive'],
    screenId: 'EBLDOC120U',
    name: '전송 이력 조회',
    type: '화면',
    desc: '전송 이력 조회(송/수신일시, 수신인, BL상태 등)',
    completedAt: '2026-02-03',
    mobileApply: '필수 적용',
    mobileAttr: 'Body',
    mobileCompletedAt: '2026-02-28',
    nature: '공통',
  },

  // ========== eBL서비스 (공통) Partners ==========
  {
    service: 'ebl',
    userType: [],
    levels: ['Partners'],
    screenId: 'EBLPAT010U',
    name: '파트너 관리',
    type: '화면',
    desc: '파트너 관리 통합 화면 (탭: Contacts / My Invitations / Carrier ID Mapping)',
    completedAt: '2026-01-31',
    mobileApply: '미적용',
    mobileAttr: 'N/A',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: [],
    levels: ['Partners', 'Contacts'],
    screenId: 'EBLPAT010U',
    name: '나의 파트너 조회',
    type: '탭',
    desc: '나의 파트너 조회 목록',
    completedAt: '2026-01-31',
    mobileApply: '미적용',
    mobileAttr: 'N/A',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: [],
    levels: ['Partners', 'Contacts', 'Partners Detail'],
    screenId: 'EBLPAT020P',
    parentScreenId: 'EBLPAT010U',
    name: '나의 파트너 상세',
    type: '다이얼로그',
    desc: '역할(수출자, 수입자, 은행 등) 및 회사 정보(담당자, 연락처 등)',
    completedAt: '2026-01-31',
    mobileApply: '미적용',
    mobileAttr: 'N/A',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: [],
    levels: ['Partners', 'Contacts', 'Add Partners'],
    screenId: 'EBLPAT030P',
    parentScreenId: 'EBLPAT010U',
    name: '신규 파트너 추가',
    type: '다이얼로그',
    desc: '신규 파트너 추가',
    completedAt: '2026-01-31',
    mobileApply: '미적용',
    mobileAttr: 'N/A',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: [],
    levels: ['Partners', 'Contacts', 'Add Partners', 'Potential Partners'],
    screenId: 'EBLPAT060P',
    parentScreenId: 'EBLPAT010U',
    name: '포털 사용자 조회',
    type: '다이얼로그',
    desc: '포털에 가입된 사용자 조회',
    completedAt: '2026-01-31',
    mobileApply: '미적용',
    mobileAttr: 'N/A',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: [],
    levels: ['Partners', 'My Invitations'],
    screenId: 'EBLPAT050U',
    parentScreenId: 'EBLPAT010U',
    name: '초대장 발송 이력 조회',
    type: '탭',
    desc: '수신인별 초대장 발송 이력 및 수신 상태 조회 (메일 도착상태, 읽음표시)',
    completedAt: '2026-01-31',
    mobileApply: '미적용',
    mobileAttr: 'N/A',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: [],
    levels: ['Partners', 'My Invitations', 'Invitation Detail'],
    screenId: 'EBLPAT070P',
    parentScreenId: 'EBLPAT010U',
    name: '초대장 상세',
    type: '다이얼로그',
    desc: '초대장 발송 상세 정보',
    completedAt: '2026-01-31',
    mobileApply: '미적용',
    mobileAttr: 'N/A',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: [],
    levels: ['Partners', 'My Invitations', 'Create Invitation'],
    screenId: 'EBLPAT040P',
    parentScreenId: 'EBLPAT010U',
    name: '초대장 발송',
    type: '다이얼로그',
    desc: '파트너 정보 입력 후 포털 가입 초대장 발송',
    completedAt: '2026-01-31',
    mobileApply: '미적용',
    mobileAttr: 'N/A',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: ['화주', '은행'],
    levels: ['Partners', 'Carrier ID Mapping'],
    screenId: 'EBLSET020U',
    parentScreenId: 'EBLPAT010U',
    name: '선사 ID 관리',
    type: '탭',
    desc: 'HMM 외의 선사의 경우 화주 ID, 선사 ID 매핑 관리',
    completedAt: '2026-01-31',
    mobileApply: '미적용',
    mobileAttr: 'N/A',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: ['화주', '은행'],
    levels: ['Partners', 'Carrier ID Mapping', 'Mapping'],
    screenId: 'EBLSET030P',
    parentScreenId: 'EBLPAT010U',
    name: '선사 ID 매핑',
    type: '다이얼로그',
    desc: 'HMM 외의 선사의 경우 화주 ID, 선사 ID 매핑 기능',
    completedAt: '2026-01-31',
    mobileApply: '미적용',
    mobileAttr: 'N/A',
    nature: '공통',
  },

  // ========== eBL서비스 (공통) Sub Users ==========
  {
    service: 'ebl',
    userType: [],
    levels: ['Settings', 'My Company', 'Co-worker'],
    screenId: 'EBLSUB010U',
    parentScreenId: 'EBLSET060U',
    name: '서브 사용자 목록 조회',
    type: '화면',
    desc: '등록된 모든 서브 사용자 리스트 조회, 페이지 분리 및 추가 작업예정',
    completedAt: '2026-03-19',
    mobileApply: '필수 적용',
    mobileAttr: 'Body',
    mobileCompletedAt: '2026-03-02',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: [],
    levels: ['Settings', 'My Company', 'Co-worker', 'Users Detail'],
    screenId: 'EBLSUB060P',
    parentScreenId: 'EBLSET060U',
    name: '서브 사용자 상세',
    type: '팝업화면',
    desc: '사용자 정보 노출, 사용권한 설정: Active(정상), Inactive(사용중지), 페이지 분리 및 추가 작업예정',
    completedAt: '2026-03-19',
    mobileApply: '필수 적용',
    mobileAttr: 'Pop Up',
    mobileCompletedAt: '2026-03-02',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: [],
    levels: ['Sub Users', 'Directory', 'Users Detail', 'Reset password'],
    screenId: 'EBLSUB030P',
    parentScreenId: 'EBLSET060U',
    name: '패스워드 변경',
    type: '팝업화면',
    desc: '신규 비밀번호, 비밀번호 확인 입력, 페이지 분리 및 추가 작업예정',
    completedAt: '2026-03-19',
    mobileApply: '필수 적용',
    mobileAttr: 'Pop Up',
    mobileCompletedAt: '2026-03-02',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: [],
    levels: ['Settings', 'My Company', 'Co-worker', 'Add Users'],
    screenId: 'EBLSUB020P',
    parentScreenId: 'EBLSET060U',
    name: '서브 사용자 추가',
    type: '팝업화면',
    desc: '서브 사용자 추가, 페이지 분리 및 추가 작업예정',
    completedAt: '2026-01-31',
    mobileApply: '미적용',
    mobileAttr: 'N/A',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: [],
    levels: ['Sub Users', 'Users Log'],
    screenId: 'EBLSUB040T',
    name: '사용자 업무 활동 기록 조회',
    type: '탭',
    desc: '해당 사업자 소속 전체 사용자의 업무 내역 조회, 페이지 분리 및 추가 작업예정',
    completedAt: '2026-01-31',
    mobileApply: '필수 적용',
    mobileAttr: 'N/A',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: [],
    levels: ['Sub Users', 'Users Log', 'Audit Log'],
    parentScreenId: 'EBLSUB040T',
    screenId: 'EBLSUB050T',
    name: '사용자 보안접속 이력 조회',
    type: '탭',
    desc: '모든 사용자(로그인 계정)의 로그인 이력 조회, 페이지 분리 및 추가 작업예정',
    completedAt: '2026-01-31',
    mobileApply: '필수 적용',
    mobileAttr: 'N/A',
    nature: '공통',
  },

  // ========== eBL서비스 (공통) Notifications ==========
  {
    service: 'ebl',
    userType: [],
    levels: ['Notifications'],
    screenId: 'EBLNOT010U',
    name: '알림 목록',
    type: '화면',
    desc: '모바일 알림 목록 화면, PC는 앱바 메뉴로 제공',
    completedAt: '2026-04-08',
    hide: 'pc',
    mobileApply: '필수 적용',
    mobileAttr: 'Body',
    mobileCompletedAt: '2026-04-08',
    nature: '특화',
  },

  // ========== eBL서비스 (공통) Settings ==========
  {
    service: 'ebl',
    userType: [],
    levels: ['Settings'],
    screenId: 'EBLSET040U',
    name: '환경 설정',
    type: '화면',
    desc: '내 정보 관리 / 비밀번호, 연락처, 직책, 부서, 프로필 사진 업로드 등',
    completedAt: '2026-01-31',
    mobileApply: '미적용',
    mobileAttr: 'N/A',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: [],
    levels: ['Settings', 'My profile'],
    screenId: 'EBLSET010U',
    name: '내 정보 관리',
    type: '화면',
    desc: '이용 환경 설정, 알림 설정 - 사용자별 알림 이벤트 선택',
    completedAt: '2026-01-31',
    mobileApply: '축소 적용',
    mobileAttr: 'Body',
    mobileCompletedAt: '2026-03-03',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: [],
    levels: ['Settings', 'My Company'],
    screenId: 'EBLSET060U',
    name: '회사 정보',
    type: '화면',
    desc: '회사 정보 관리, 페이지 분리 및 추가 작업예정',
    completedAt: '2026-03-19',
    mobileApply: '필수 적용',
    mobileAttr: 'Body',
    mobileCompletedAt: '2026-03-02',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: [],
    levels: ['Settings', 'Notification Settings'],
    screenId: 'EBLCST090U',
    name: '알림 설정',
    type: '화면',
    desc: '알림 관련 설정 화면, 모바일 완료!',
    completedAt: '2026-03-19',
    mobileApply: '필수 적용',
    mobileAttr: 'Body',
    mobileCompletedAt: '2026-03-03',
    nature: '공통',
  },
  // EBLSET020U, EBLSET030P → Partners > Carrier ID Mapping 탭으로 통합 이전 (위 Partners 섹션 참조)

  {
    service: 'ebl',
    userType: ['선사'],
    levels: ['Settings', 'Carrier Management'],
    screenId: 'EBLCST010U',
    name: '선사 설정 관리',
    type: '화면',
    desc: '선사 설정 통합 화면 (탭: Routes / Terms & Conditions / Signatures / Containers)',
    completedAt: '2026-01-31',
    mobileApply: '미적용',
    mobileAttr: 'N/A',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: ['선사'],
    levels: ['Settings', 'Carrier Management', 'Routes'],
    screenId: 'EBLCST010U',
    parentScreenId: 'EBLCST010U',
    name: '출도착지 관리',
    type: '탭',
    desc: '출도착지 관리 목록 조회',
    completedAt: '2026-01-31',
    mobileApply: '미적용',
    mobileAttr: 'N/A',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: ['선사'],
    levels: ['Settings', 'Carrier Management', 'Routes', 'Add Departure/Arrival'],
    screenId: 'EBLCST080P',
    parentScreenId: 'EBLCST010U',
    name: '출도착지 등록',
    type: '다이얼로그',
    desc: '지역 코드, 지역명 선택',
    completedAt: '2026-01-31',
    mobileApply: '미적용',
    mobileAttr: 'N/A',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: ['선사'],
    levels: ['Settings', 'Carrier Management', 'Terms & Conditions'],
    screenId: 'EBLCST020U',
    parentScreenId: 'EBLCST010U',
    name: '이면약관 관리',
    type: '탭',
    desc: '이면약관(공통약관) 관리 목록 조회',
    completedAt: '2026-01-31',
    mobileApply: '미적용',
    mobileAttr: 'N/A',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: ['선사'],
    levels: ['Settings', 'Carrier Management', 'Terms & Conditions', 'T&C Reg/View'],
    screenId: 'EBLCST030P',
    parentScreenId: 'EBLCST010U',
    name: '이면약관 등록/상세',
    type: '다이얼로그',
    desc: '이면약관(공통약관) 신규등록/수정/상세내용조회',
    completedAt: '2026-01-31',
    mobileApply: '미적용',
    mobileAttr: 'N/A',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: ['선사'],
    levels: ['Settings', 'Carrier Management', 'Signatures'],
    screenId: 'EBLCST040U',
    parentScreenId: 'EBLCST010U',
    name: '서명 관리',
    type: '탭',
    desc: '선사의 서명 이미지 등록 관리',
    completedAt: '2026-01-31',
    mobileApply: '미적용',
    mobileAttr: 'N/A',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: ['선사'],
    levels: ['Settings', 'Carrier Management', 'Signatures', 'Add Sign'],
    screenId: 'EBLCST050P',
    parentScreenId: 'EBLCST010U',
    name: '서명 등록',
    type: '다이얼로그',
    desc: '선사의 서명 이미지 등록 다이얼로그',
    completedAt: '2026-01-31',
    mobileApply: '미적용',
    mobileAttr: 'N/A',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: ['선사'],
    levels: ['Settings', 'Carrier Management', 'Containers'],
    screenId: 'EBLCST060U',
    parentScreenId: 'EBLCST010U',
    name: 'Container 관리',
    type: '탭',
    desc: '공통코드의 Container Code 내역을 불러와서 선사용으로 관리한다.',
    completedAt: '2026-01-31',
    mobileApply: '미적용',
    mobileAttr: 'N/A',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: ['선사'],
    levels: ['Settings', 'Carrier Management', 'Containers', 'Modify Container Type'],
    screenId: 'EBLCST060P',
    parentScreenId: 'EBLCST010U',
    name: 'Container 수정',
    type: '다이얼로그',
    desc: '공통코드의 Container Code 내역을 선사용으로 수정한다.',
    completedAt: '2026-01-31',
    mobileApply: '미적용',
    mobileAttr: 'N/A',
    nature: '공통',
  },

  // ========== eBL서비스 (공통) Favorites ==========
  {
    service: 'ebl',
    userType: [],
    levels: ['Favorites'],
    screenId: 'EBLFAV010U',
    name: '즐겨찾기',
    type: '화면',
    desc: '즐겨찾기 설정한 대상 메뉴 목록 조회',
    completedAt: '2026-01-31',
    mobileApply: '미적용',
    mobileAttr: 'N/A',
    nature: '공통',
  },

  // ========== eBL서비스 (공통) User Guides ==========
  {
    service: 'ebl',
    userType: [],
    levels: ['User Guides', 'Notices'],
    screenId: 'EBLUGD080U',
    name: '공지사항',
    type: '화면',
    desc: '서비스 공지사항 목록 조회 및 상세 확인',
    completedAt: '2026-04-13',
    mobileApply: '필수 적용',
    mobileAttr: 'Body',
    mobileCompletedAt: '2026-03-05',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: [],
    levels: ['User Guides', 'FAQ'],
    screenId: 'EBLUGD020U',
    name: '자주하는 질문',
    type: '화면',
    desc: '사용법 관련 자주 묻는 질문 정리',
    completedAt: '2026-01-31',
    mobileApply: '필수 적용',
    mobileAttr: 'Body',
    mobileCompletedAt: '2026-03-05',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: [],
    levels: ['Help Desk', 'Download'],
    screenId: 'EBLUGD030U',
    name: 'Download',
    type: '화면',
    desc: 'Download',
    completedAt: '2026-01-31',
    mobileApply: '필수 적용',
    mobileAttr: 'Body',
    mobileCompletedAt: '2026-03-05',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: [],
    levels: ['Help Desk', 'Download', 'Download Detail'],
    screenId: 'EBLUGD070P',
    parentScreenId: 'EBLUGD030U',
    name: 'Download Detail',
    type: '팝업화면',
    desc: '자료 상세 내용, 자료 다운로드',
    completedAt: '2026-01-31',
    mobileApply: '필수 적용',
    mobileAttr: 'Pop Up',
    mobileCompletedAt: '2026-03-05',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: [],
    levels: ['User Guides', 'Q&A'],
    screenId: 'EBLUGD040U',
    name: '사용자 문의',
    type: '화면',
    desc: 'Q&A 담당자 문의 문의/제안 게시물 목록 조회',
    completedAt: '2026-01-31',
    mobileApply: '필수 적용',
    mobileAttr: 'Body',
    mobileCompletedAt: '2026-03-05',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: [],
    levels: ['User Guides', 'Q&A', 'Q&A Details'],
    screenId: 'EBLUGD050P',
    parentScreenId: 'EBLUGD040U',
    name: '사용자 문의 상세',
    type: '팝업화면',
    desc: '문의 내용 확인 및 Q&A 담당자의 답변 노출',
    completedAt: '2026-01-31',
    mobileApply: '필수 적용',
    mobileAttr: 'Pop Up',
    mobileCompletedAt: '2026-03-05',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: [],
    levels: ['User Guides', 'Q&A', 'Q&A Register'],
    screenId: 'EBLUGD060P',
    parentScreenId: 'EBLUGD040U',
    name: '사용자 문의 등록',
    type: '팝업화면',
    desc: 'Q&A 담당자에게 문의 유형 및 내용을 입력하여 등록',
    completedAt: '2026-01-31',
    mobileApply: '필수 적용',
    mobileAttr: 'Pop Up',
    mobileCompletedAt: '2026-03-05',
    nature: '공통',
  },

  // ========== eBL서비스 (공통) Payments ==========
  {
    service: 'ebl',
    userType: [],
    levels: ['Payments', 'Payment History'],
    screenId: 'EBLPAY010U',
    name: '결제내역 조회',
    type: '화면',
    desc: '결제내역 조회 (Payment History + Account Balance 탭 구성) / 사용량 및 결제이력 조회 / 잔액 변동 내역(차감/충전/복원) 조회',
    completedAt: '2026-01-31',
    mobileApply: '필수 적용',
    mobileAttr: 'Body',
    mobileCompletedAt: '2026-03-05',
    nature: '공통',
  },
  // {
  //   service: 'ebl',
  //   userType: [],
  //   levels: ['Payments', 'Payment History', 'Billing Detail'],
  //   screenId: 'EBLPAY040P',
  //   parentScreenId: 'EBLPAY010U',
  //   name: '청구서 상세',
  //   type: '팝업화면',
  //   desc: '월별로 청구된 상세 내역',
  //   completedAt: '2026-01-31',
  //   mobileApply: '필수 적용',
  //   mobileAttr: 'Pop Up',
  //   mobileCompletedAt: '2026-03-05',
  //   nature: '공통',
  // },
  {
    service: 'ebl',
    userType: [],
    levels: ['Payments', 'Account Balance'],
    screenId: 'EBLPAY020U',
    parentScreenId: 'EBLPAY010U',
    name: '잔액 현황',
    type: '탭(EBLPAY010U 종속)',
    desc: '차감내역/ 복원내역 등의 내역을 조회할 수 있는 화면 필요 / BL /파일 전송시 송신자가 비용지불, 수신자가 수신 거절시 금액 복원되어야 함 / 충전금액 조회',
    completedAt: '2026-01-31',
    mobileApply: '필수 적용',
    mobileAttr: 'Body',
    mobileCompletedAt: '2026-03-05',
    nature: '공통',
  },
  // {
  //   service: 'ebl',
  //   userType: [],
  //   levels: ['Payments', 'Register Coupon'],
  //   screenId: 'EBLPAY030P',
  //   parentScreenId: 'EBLPAY020U',
  //   name: '쿠폰 등록',
  //   type: '팝업화면',
  //   desc: '쿠폰번호를 입력하여 쿠폰 등록 / 이메일로 쿠폰 번호 전송',
  //   completedAt: '2026-01-31',
  //   mobileApply: '미적용',
  //   mobileAttr: 'N/A',
  //   nature: '공통',
  // },

  // ========== eBL서비스 (화주/은행) eNego Management ==========
  {
    service: 'ebl',
    userType: ['화주', '은행'],
    levels: ['eNego Management', 'eNego List'],
    screenId: 'EBLNEG010U',
    name: 'eBL 매입 현황',
    type: '화면',
    desc: 'eNego 매입현황조회(API연계) 목록. 상세내용 화면, 기간검색, 신용장번호검색 등의 내용으로 검색',
    completedAt: '2026-01-31',
    mobileApply: '필수 적용',
    mobileAttr: 'Body',
    mobileCompletedAt: '2026-03-03',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: ['화주', '은행'],
    levels: ['eNego Management', 'eNego List', 'eNego Detail'],
    screenId: 'EBLNEG050P',
    parentScreenId: 'EBLNEG010U',
    name: '매입 상세',
    type: '팝업',
    desc: 'EBLNEG010U 화면에서 선택한 상세정보 오픈',
    completedAt: '2026-01-31',
    mobileApply: '필수 적용',
    mobileAttr: 'Pop Up',
    mobileCompletedAt: '2026-03-03',
    nature: '공통',
  },

  {
    service: 'ebl',
    userType: ['화주', '은행'],
    levels: ['eNego Management', 'eNego List', 'Presentation'],
    screenId: 'EBLNEG030U',
    parentScreenId: 'EBLNEG010U',
    name: '매입서류 관리',
    type: '탭(EBLNEG010U 종속)',
    desc: 'EBLNEG010U 화면 내 Presentation 탭(개설은행 승인/반려)',
    completedAt: '2026-01-31',
    mobileApply: '필수 적용',
    mobileAttr: 'Body',
    mobileCompletedAt: '2026-03-03',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: ['화주', '은행'],
    levels: ['eNego Management', 'eNego List', 'Presentation', 'Presentation Detail'],
    screenId: 'EBLNEG060P',
    parentScreenId: 'EBLNEG010U',
    name: '매입서류 상세',
    type: '팝업',
    desc: '',
    completedAt: '2026-01-31',
    mobileApply: '필수 적용',
    mobileAttr: 'Pop Up',
    mobileCompletedAt: '2026-03-03',
    nature: '공통',
  },
  {
    service: 'ebl',
    userType: ['화주', '은행'],
    levels: [
      'eNego Management',
      'eNego List',
      'Presentation',
      'Presentation Detail',
      'Reason for Rejection',
    ],
    screenId: 'EBLNEG040P',
    parentScreenId: 'EBLNEG010U',
    name: '거절 사유',
    type: '팝업',
    desc: '',
    completedAt: '2026-01-31',
    mobileApply: '필수 적용',
    mobileAttr: 'Pop Up',
    mobileCompletedAt: '2026-03-03',
    nature: '공통',
  },

  // ========== eBL서비스 (공통) Main Menu ==========
  {
    service: 'ebl',
    userType: [],
    levels: ['Main Menu'],
    screenId: 'EBLMME010P',
    name: '전체 메뉴',
    type: '팝업화면',
    desc: '레이어 팝업 형태로 전체 메뉴 노출',
    completedAt: '2026-01-31',
    mobileApply: '필수 적용',
    mobileAttr: 'Body',
    mobileCompletedAt: '2026-03-03',
    nature: '특화',
  },
].map((item) => ({
  ...item,
  mobileCompletedAt: item.mobileCompletedAt ?? '',
  mobileDueAt: item.mobileDueAt ?? (item.service === 'ebl' ? DEFAULT_MOBILE_DUE_AT : ''),
}))
